#!/bin/bash

set -euo pipefail

echo $BUILDKITE_PLUGIN_PIPELINE_TEMPLATE_TEAM

cat $(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)/../required-steps-pre.yml > output.yaml
cat .buildkite/pipeline.yaml >> output.yaml
cat $(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)/../required-steps-post.yml >> output.yaml
cat output.yaml | buildkite-agent pipeline upload

