#!/bin/bash

set -euo pipefail

if [ -z "$BUILDKITE_PLUGIN_PIPELINE_TEMPLATE_TEAM" ]
then
  echo "Plugin 'team' parameter must be set"
else
  TEAM=$BUILDKITE_PLUGIN_PIPELINE_TEMPLATE_TEAM
  echo $TEAM
fi

echo "steps:" > output.yaml
cat $(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)/../required-steps/required-steps-pre.yml >> output.yaml
cat .buildkite/pipeline.yaml >> output.yaml
cat $(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)/../required-steps/required-steps-post.yml >> output.yaml
cat output.yaml
cat output.yaml | buildkite-agent pipeline upload

